/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MocksController {
  /**
   * Create a new controller manager
   *
   * @param collectionsPath - Path or glob pattern to collections file(s)
   * @param routesPath - Path or glob pattern to routes file(s)
   * @param defaultCollection - Optional default collection ID
   */
  constructor(collectionsPath: string, routesPath: string, defaultCollection?: string | undefined | null)
  /** Apply a collection by ID */
  useCollection(collectionId: string): void
  /** Get current collection ID */
  get currentCollection(): string | null
  /** Get all active routes (HTTP + WS) */
  getActiveRoutes(): Array<ActiveRoute>
}

/** Mocks Manager class */
export declare class MocksManager {
  /**
   * Create a new mocks manager
   *
   * @param collectionsPath - Path or glob pattern to collections file(s)
   * @param routesPath - Path or glob pattern to routes file(s)
   * @param basePath - Optional base directory for resolving relative paths
   */
  constructor(collectionsPath: string, routesPath: string)
  /** Resolve collection with inheritance and return active routes */
  resolveCollection(collectionId: string): Array<ActiveRoute>
}

export interface ActiveRoute {
  route: Route
  preset: Preset
  variant: Variant
}

/** Collection of routes */
export interface Collection {
  id: string
  from?: string
  routes: Array<string>
}

/** HTTP method for route matching */
export declare const enum HttpMethod {
  Get = 0,
  Post = 1,
  Put = 2,
  Patch = 3,
  Delete = 4,
  Head = 5,
  Options = 6
}

/** Request matching preset */
export interface Preset {
  id: string
  variants: Array<Variant>
  headers?: Record<string, string>
  query?: Record<string, string>
  queryExpr?: string
  params?: Record<string, string>
  payload?: any
  payloadExpr?: string
}

/** Route definition */
export interface Route {
  id: string
  url: string
  transport: Transport
  method?: HttpMethod
  presets: Array<Preset>
}

/** Transport type for route matching */
export declare const enum Transport {
  Http = 0,
  WebSocket = 1
}

/** Response variant */
export interface Variant {
  id: string
  status?: number
  headers?: Record<string, string>
  body?: any
}

/** Library version */
export declare function version(): string
